apiVersion: v1
kind: Service
metadata:
  name: skin-disease-prediction-service
spec:
  type: NodePort
  selector:
    app: skin-disease-prediction
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
